name: 'Generate Release Hashes'
author: 'JackMacWindows'
description: 'A GitHub action to automatically generate a list of hashes for a release.'
inputs:
  hash-type:
    description: 'Type of hash to generate (md5, sha1, sha256, sha512)'
    required: false
    default: 'sha256'
  file-name:
    description: 'File name to save as if desired'
    required: false
    default: ''
  get-assets:
    description: 'Whether to redownload the asset list (useful if previous jobs upload other assets)'
    required: false
    default: 'false'
outputs:
  hashes:
    description: 'A string with the resulting hashes, one per line, with file name followed by hash'
runs:
  using: 'node16'
  main: 'index.js'
branding:
  icon: 'hash'
  color: 'green'